### ISSUE TITLE
식당에서 밥먹었는지 detect

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#12]
식사시간대(12:00~13:30, 18:00~19:30)에는 일정간격(5분?)마다 Wifi SSID를 검사해서 "SKP-GUEST"가 잡히면 사내 식당에서 밥을 먹은 것으로 간주하고 평가요청 notification을 띄워봅시다.
- Wifi를 끄고 다니는 사람이 많을 경우 무용지물이 되므로, v1.0에서는 먼저 해당 시간에 Wifi가 켜져있는지 꺼져있는지만 조사하는 게 좋겠네요.

**Comment by bigapple01** [comment]
와이파이 기준의 노티는 좀 어노잉할 수도 있다고 생각합니다. 다른 필터링 요소가 추가되거나, 시간대를 줄이거나(외식파의 복귀 시점 이전까지), 특정 두 시점에서 모두 SSID가 'SKP-GUEST'로 잡혔다거나 등등...

**Comment by hkjinlee** [comment]
좋은 지적입니다! 당장 메모해두자는 의미에서 일단 적어둔 것이고, 실제 구현 로직은 위처럼 단순하면 안되겠죠 :)

**Comment by hkjinlee** [comment]
#48 이슈로 갈음합니다. Wifi SSID보다는 비콘이 좀더 정확할 듯.
