### ISSUE TITLE
웹사이트 개발범위 지정

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#20]
# 웹사이트가 필요한가?
## 사용자 측면: 웹이 접근할 수 있는 사용자층이 더 넓다.
- 아이폰 사용자 커버 ( 최소한 식단 매뉴랑 별점 현황/랭킹 정도는 보여주자)
- 앱을 깔지 않은 안드로이드 사용자 커버
- 데스트톱 사용자 커버 
## 테스트 측면
- MP를 활용한 GA 통합 
  - 웹에 이벤트 또는 공지사항 페이지를 작성하고, 앱을 열었을 때 동일한 session으로 묶어보자 
- 웹에서 구글 로그인 > 앱 다운로드 기능
- 디자인 테스트: 웹에서 디자인을 먼저 퍼블리싱 해서 만들어복 괜찮으면 앱에도 참고
# 정리하다 보니..
- 걍 만들고 싶은듯; 
- 혼자 만들어야 하니깐 버전은 2.0 정도로..

**Comment by hkjinlee** [comment]
푸쉬메시지 타잎 정리하다보니, 티스토어랑 마찬가지로 webview에서 뜨는 이벤트 푸시 보낼 일이 가끔 있을 듯하네요. 런칭이벤트로 메뉴평점 많이 올려주신 분들 중 일부에게 10층 식당 식권 드리는 이벤트를 기획하고, 이쪽 안내페이지를 웹뷰로 만들면 어때요? (식권비용은 50만원 지원금에서 충당)

그렇게 하면 모바일웹쪽 작업 먼저 진행하다가 런칭 즈음해서 webview에 넣고 tracking session 묶는 작업 진행하면 될 듯. 1.0에 넣어서 진행해볼 수 있지 않겠어요?

**Comment by dusskapark** [comment]
음, 웹의 상단 GNB를 오늘의 매뉴 / 이벤트 정도로 구분하겠습니다.
이벤트 및 공지사항을 작성할 수 있도록 하겠습니다. (몽땅 다 만드는 것은 하기 힘드니깐 Tistory 쪽을 살펴보고 있습니다.)

2015년 10월 22일 (목) 오후 1:03, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
http://bobplanet.github.io/ 에 테스트 페이지 올려뒀습니다.
소스는 https://github.com/bobplanet/bobplanet.github.io 참조.

GitHub Pages가 [Jekyll](http://jekyllrb.com/)이라는 페이지생성기를 지원하는데, 그냥 PC에서 html 파일 수정해서 github에 push하기만 하면 알아서 다 해주니까 별도 서버도 필요없고 아주 편하네요.

아예 홈페이지 팀을 하나 따로 만들까봐...

**Comment by dusskapark** [comment]
괜찮을 것 같습니다. 괜찮으시면 저랑 한두명을 역할 지정해서 역할을 지정해주시면 맞춰서 달리겠습니다. (원래 생각대로 두식 매니저가
기획하고; 제가 개발해볼까요? :)

2015년 10월 26일 (월) 오전 12:01, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
츨근길에 jekyll 관련글을 좀 읽어봤는데, jekyll + github pages 조합이 꽤 괜찮네요. 일단 무료고, 그냥 HTML 페이지라 서버코딩 필요없고, 블로그 포스트는 markdown으로 만들어 파일로 떨궜다가 git push하면 서버에 자동반영되고...

코멘트 기능을 사용하려면 disqus 같은 걸 써야하는데, 코멘트가 필요할지는 내일 얘기해보죠.

**Comment by dusskapark** [comment]
지난주에 생각했던 Tistory를 사용하는 것이랑 jekyll + github pages 조합으로 아예 페이지를 만드는 것 중에서
하나를 선택하면 어떨까 합니다.
장단점이 명확한데, Tistory 는 코드 접근성이 떨어져도 이런것저런 것을 해볼 수 있게 해준다는 점이 장점이지만 반대로 코드
자유도가 확실히 떨어집니다. 직접 페이지를 만드는 것이랑은 딱 이런차이가 있어 보입니다.

2015년 10월 26일 (월) 오전 9:18, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
HTML을 직접 수정할 수 있는 github pages쪽이 저는 더 괜찮아보이네요. 대략 아래와 같은 제품소개 중심의 페이지를 만들 필요가 있다고 보는데요, tistory가 이런 사이트에 적합할까요?

https://www.wunderlist.com/ko/
http://home.playwings.co.kr/
https://www.duolingo.com/
https://www.pushbullet.com/
https://send-anywhere.com/

**Comment by dusskapark** [comment]
- onGoing 하게 이벤트, 공지사항 등 운영을 꾸준히 할 것인지? 변수가 될 것 같습니다.
  - 만약 운영을 한다면, Tistory를 twik 하는 것이 장기적으로 운영에 편리합니다. (매번 퍼블리싱을 안해도 되고 에디터도
    강력한 편이고..)
- 음.. 깃헙 페이지로 일단 다 만들고 나중에 또 필요해지면 수정을 하는 것도 좋을 것 같습니다.

2015년 10월 26일 (월) 오후 2:06, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
@dusskapark http://bobplanet.kr/menu.html 에 서버에서 메뉴정보 불러오는 예제 페이지 만들어 뒀습니다. 동작에 특별한 문제는 없는데, 다음검색 API에서 가져온 이미지가 불펌으로 엑박 뜨는 이슈가 있네요.

사용한 라이브러리: http://handlebarsjs.com/

**Comment by dusskapark** [comment]
Pin 했습니다. 학습하고 다음주 쯤 까지 뭔가 작성해 와야겠네요 ㅇㅇ @DoosikKim

2015년 10월 29일 (목) 오전 1:25, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by dusskapark** [comment]
지난 화요일 플라랩에서 범위 정의가 완료됐습니다.
