### ISSUE TITLE
컬러코드 및 화면UI tweak

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#26]
- 전체적인 디자인은 Material design guide를 따름 (https://www.google.com/design/spec/style/color.html  참조)
- 컬러코드는 좀더 vivid한 톤으로 진행: 아래 사이트 참조
  - http://www.materialui.co/colors
  - http://www.materialpalette.com/

**Comment by hkjinlee** [comment]
오늘 @sjs1178 님께서 아래와 같은 디자인을 잡아주셨는데.. 몇가지 의견 보탭니다.

![main_fold](http://songjinseok.com/bobp/bobp_main_fold.jpg)
- 좋아요/싫어요 현황과 버튼의 통합
  - 카드 우측 하단의 +107/-30(현재 현황)을 아예 아래로 내려서 '좋아요'/'싫어요' 옆에 넣어버리면 어때요?
  - [ 乃 좋아요(+107) ] [ 乃 싫어요(-30) ] => 이렇게 두고, 사용자가 누르면 숫자가 1 증가하는 형태
- 좋아요 vs 싫어요를 시각적으로 대비시킬 수 있는 visual cue 도입
  - '좋아요' 버튼과 '싫어요' 버튼 안에 숫자 외에도 색상 등을 이용한 시각적 대비요소가 있으면 좋을 것 같아요.
  - 투표가 많을수록 배경색을 더 선명하게 하는 방법이 있을 수 있는데, 이건 버튼색상의 일관성을 해치니 제외
  - 가운데 부분에 저울 이미지를 넣고 더 강한 쪽으로 기울어지는 형태를 제안해 봅니다.

**Comment by hkjinlee** [comment]
@sjs1178 다만 화면의 fold/unfold는 좋은지 모르겠습니다. (개인적으로 unfold된 상태에서 다시 fold상태로 돌아가려는 의도로 무의식중에 back을 눌렀다가 아예 이전화면으로 가버린 경우가 있었음) 혹시 좋은 사례가 있으면 앱 다운로드 링크 하나 걸어주세요.

**Comment by dusskapark** [comment]
- 이미지 관련
  - 이미지 사이즈를 줄여도 될까요? 이미지를 전면으로 꽉채워봤는데, 가끔 해상도 떨어지는 것이 있어서 이상하게 보일 때가 있습니다. 
  - 위와 같은 이유로 그위에 글씨를 쓰는 것도 최소화 하는 것이 어떨까.. (낮은 해상도에 흰색 글씨는.. 지양하는 것이 좋을 것 같습니다.)
  - 대신 하단에 글씨를 충분히 노출할 수 있는 공간을 만들고 활용하면 어떨까.. 합니다. 
  - 웹에서는 부족한 공간은 카드 뒤집기 (reveal) 액션으로 처리하면 어떨까.. 합니다.

![screen shot 2015-10-27 at 6 01 22 pm](https://cloud.githubusercontent.com/assets/4177529/10753504/c68bc6ae-7cd4-11e5-8fa4-ab748faa00b7.png)

> ~~이미 만든 카드 디자인의 재탕같지만;; 진짜 의견입니다~~

**Comment by hkjinlee** [comment]
@dusskapark 이미지 해상도는 충분히 높을텐데 이상하네요.
가자미구이 이미지: http://postfiles14.naver.net/20150331_61/livlong_1427777960575mTgJl_PNG/DSC09877.png?type=w1 (900x504)
썸네일:
https://t3.search.daumcdn.net/argon/130x130_85_c/EtQfaXXSxWQ

https://console.developers.google.com/project/kr-bobplanet/datastore/query?authuser=0&queryType=KindQuery&namespace=&kind=Item 접속하면 현재 식단 데이터 볼 수 있습니다.

**Comment by dusskapark** [comment]
안녕하세요 박주형 입니다.

현재 컬러코드가 정해진 것인지요? 
일단 유사한 색으로 작업하고 있겠습니다.

**Comment by hkjinlee** [comment]
@dusskapark 찌찌뽕! 지금 컬러코드 바꿔야하나 고민하고 있었는데요 :)

진석매니저가 낸 아이디어 중에서 '좋아요'는 초록색, '싫어요'는 붉은색은 차용하려고 해요. 이렇게 되면 visual cue로 '신호등'을 사용할 수 있게 되더군요. 대충 이런 느낌으로 만들어볼 생각:
http://www.shutterstock.com/pic-13236319/stock-vector-horizontal-traffic-light-variants-vector-illustration-isolated-on-white-background.html?src=6KOu0XlIoUKdI6onrqwtLg-1-3

그런데 이렇게 green / red를 써먹을 경우 key color code는 붉은 색 계열에서 벗어나는 게 나을 듯한 생각이 들어 고민중.

**Comment by dusskapark** [comment]
OVEN을 활용하는 다른 일감이 있어서 본 일감을 마감합니다.
