### ISSUE TITLE
bobplanet.kr 도메인 등록

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#28]
정식으로 도메인 등록해서 http://bobplanet.github.io/ 를 이쪽으로 연결합시다.

도메인: bobplanet.kr (다른 도메인이 필요할까요?)
등록기간: 1년
등록비: 팀 지원금에서 충당 (이건 Plalab 비용으로 처리하기 애매하네요)

@dusskapark 님, 제가 확인해보니 도메인 자체는 주인이 없는 상태입니다. 널럴할 때 구매 진행합시다 :)

**Comment by dusskapark** [comment]
집에 가는 길에 구입하겠습니다.

2015년 10월 27일 (화) 오후 5:54, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by dusskapark** [comment]
구입 후 CNAME 도 연결했습니다.

2015년 10월 27일 (화) 오후 6:08, Jude Park dusskapark@gmail.com님이 작성:

**Comment by hkjinlee** [comment]
오오 고생했음! 근데 github 이슈메일은 회신만 해도 게시판에 등록되는거냐?
2015. 10. 28. 00:01에 "Jude Park" notifications@github.com님이 작성:

**Comment by dusskapark** [comment]
네, 회신만 하면 등록됩니다.
아이콘을 자세히 보시면, 메일로 등록한 답글은 메일모양 아이콘이 있습니다 ^^

2015년 10월 28일 (수) 오전 12:04, Jin, Heonkyu notifications@github.com님이 작성:
