### ISSUE TITLE
후니드 약식인터뷰 공유

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#31]
오늘 10층식당에서 품질개선 설문조사를 하고 있길래, 식당 점장님 인터뷰를 간략히 진행했습니다.
- 이용인원수
  - 통상 조식 80~90명, 점심 560~570명, 저녁 250~260명
- 메뉴에 대한 피드백이 많지 않아 이런 앱이 있다면 대환영임
- 후니드에서는 아예 앱을 납품해달라..는 요청도 하심
  - 다른 급식사업자(에버랜드, 신세계...)와의 차별화요인이 될 수 있음
  - 참고로, 후니드가 운영하는 식당은 60~70개소

11월 중반쯤 아마 런칭하게 될 것 같다는 정보는 전해드렸더니, 필요한 지원이나 데이터가 있으면 언제든지 말씀 달라고 하시네요 :)

**Comment by dusskapark** [comment]
나중에 홍보용 영상을 하나 찍어야 하는데 후니드를 통해서 찍으면 될 것 같네요. 상세한 것은 고민해보겠습니다.
