### ISSUE TITLE
jekyll 및 materializeCSS 개발환경 구축

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#33]
- [지킬 관련 참고](https://nolboo.github.io/blog/2013/10/15/free-blog-with-github-jekyll/) 
- [materializeCSS](http://materializecss.com/)

관련 개발이 가능한 환경이 구축 및 카드를 화면에 띄워보는 것으로 진행할 것

**Comment by dusskapark** [comment]
https://github.com/polymorphic92/jekyll-Materialize

생각보다 이미 완성된 jekyll 테마를 materialize 로 수정하는 것이 쉽지는 않네요. 
아예 걍 부트스트랩 기반으로 하는 것이 낫잖을까.. 생각중입니다.

**Comment by hkjinlee** [comment]
@dusskapark 자기가 옳다고 생각하는 대로 하는 게 답이죠 :) 다만 요 며칠 사이 들었던 생각은
- 현재 제가 적용해둔 jekyll 테마를 계속 쓸 이유는 전혀 없고, 다른 걸로 대체해도 무방
- 다만, 기반기술을 무엇을 쓸 것이냐가 아니라 웹사이트의 전체 구성(제공기능, 메뉴구조)을 만드는게 중요합니다
- 저는 http://bobplanet.kr 의 역할은 정보제공이 우선이고, 기능은 나중이라고 판단.
  - 그렇게 봤을 때 [홈], [제품소개], [팀소개], [블로그(or 공지)] 정도가 핵심컨텐츠
  - [오늘의메뉴]는 제공하면 좋겠지만 여건상 안되면 나중에 개발
  - [다운로드링크], [이벤트] 등은 서브아이템이 맞지 않을까 합니다
  - [다운로드링크]는 [홈]에 들어가는 하나의 링크 수준이고,
  - [이벤트]는 [블로그]에 넣어도 별 문제 없지 않을까..
- 그렇다 하더라도 기반기술을 잘못 선택하면 향후 고생할 게 눈에 선하므로 미리 정해두는 게 좋겠죠
  - 계위상 같은 레벨은 아니나 현실적으로 materialize와 bootstrap 둘 중의 하나를 선택하는 게 맞을 듯
  - 개인적으로는 materialize는 시각적 요소간의 interaction을 정의하는데 많은 노력이 들어가므로 bootstrap 기반이 더 심플하지 않을까 싶네요
  - 보내주신 링크는 받아서 돌려봤는데, 카드 하나 덜렁 띄우는 샘플 수준이어서 이걸 사이트처럼 만들려면 한참 걸리겠네요

**Comment by dusskapark** [comment]
테마를 하나씩 머테리얼라이즈 규격으로 설정해보고 있습니다. 한 몇시간 만 더 투자를 해보고 결정을 하겠습니다 ^^

**Comment by hkjinlee** [comment]
[Yeoman](http://yeoman.io/) 기반으로 사이트 만들어보는 것도 한번 검토해봅시다.

소개자료: http://www.slideshare.net/javarouka/introduce-yeoman?qid=f4d67f97-f599-44a3-bbe7-cd557c83bf06&v=qf1&b=&from_search=1

jekyll용 코드생성기도 이미 있습니다: https://github.com/robwierzbowski/generator-jekyllrb

**Comment by dusskapark** [comment]
역할 구분: 
- 블로그 페이지 만들기 : @DoosikKim 
- 홈/제품 소개/팀 소개 만들기 : @dusskapark

이렇게 역할을 나눴습니다.

**Comment by dusskapark** [comment]
매우매우 디자인이 마음에 안들지만.. 일단은 작업한 디자인을 커밋했습니다
