### ISSUE TITLE
Facebook 광고 공유 필요하신 분은 이메일을 댓글로 달아주세요.

### ISSUE THREAD

**Issue by bigapple01** [bobplanet/Bobplanet#37]
제곧내입니다.

**Comment by hkjinlee** [comment]
heonkyu.jin@gmail.com

**Comment by dusskapark** [comment]
dusskapark@gmail.com

2015년 11월 3일 (화) 오후 3:49, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by bigapple01** [comment]
여기까지 추가 완료했습니다.

**Comment by jhh7984** [comment]
jhh7984@gmail.com
