### ISSUE TITLE
광고용 이미지 촬영

### ISSUE THREAD

**Issue by bigapple01** [bobplanet/Bobplanet#38]
점심시간 or 저녁시간의 분주한 식당 줄을 촬영.

**Comment by dusskapark** [comment]
- 이미지는 본 게시판에 올려주세요.
- 하나는 와이드스크린 (16:9) 동영상으로도 부탁드립니다..^^

2015년 11월 3일 (화) 오후 2:33, bigapple01 notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
내일은 촬영해야 실제 활용가능할 것 같네요. 
@jhh7984 님과 @bigapple01 님께서 꼭 챙겨주시기 바랍니다.

**Comment by bigapple01** [comment]
오늘 점심에 이미지 촬영하겠습니다.

**Comment by bigapple01** [comment]
https://www.dropbox.com/s/0jrxkmsbyrmxx9u/20151113_114727.jpg?dl=0
https://www.dropbox.com/s/4nsww1hkleecjvc/20151113_114753.jpg?dl=0
https://www.dropbox.com/s/ok0wz03ht211w5n/20151113_114805.jpg?dl=0
https://www.dropbox.com/s/9w2uk1yrza18j23/20151113_114828.jpg?dl=0

네 장 건졌는데, 어두워서인지 기대만큼 잘 나오진 않았습니다;; 저녁에 다시 해보든가 해야겠어요.

**Comment by hkjinlee** [comment]
아무래도 오늘 날씨가 어둑어둑해서 사진 건지긴 쉽지 않았겠네요. 고생하셨어요.
초상권 이슈 가능성이 높지 않고 줄이 길~어 보이는 2번째 아니면 3번째 사진을 썼으면 합니다.

@dusskapark 이거 홈페이지에 어떻게 넣으면 좋을까요?

**Comment by dusskapark** [comment]
parallax 로 구성된 화면에 쓰면 좋을 것 같습니다.
배경으로 쓸 수 있도록 약간 어두운 필터를 적용해서 쓰겠습니다.

2015년 11월 13일 (금) 오후 2:01, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by jhh7984** [comment]
<밥플래닛> 10층 식당에서 기다리고 있는 사진입니다. 사람도 많고 초상권 이슈도 없어보이긴 합니다만,,적정할지는 아래 링크에서 참고 부탁 드립니다.

https://www.dropbox.com/s/l8at7n5wdf0xlnn/%EB%B0%A5%ED%94%8C%EB%9E%98%EB%8B%9B_waiting.jpg?dl=0

**Comment by bigapple01** [comment]
홈피용 이미지는 건져서 일단 닫습니다.
