### ISSUE TITLE
메뉴데이터 썸네일 개선

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#39]
엉뚱한 썸네일이 들어가있거나 썸네일이 아예 없는 식당메뉴에 대한 이미지 개선이 필요합니다.

1년 전까지의 메뉴를 모두 받아두었으니 대충 나올 만한 메뉴는 다 나왔다고 보고, 현재 데이터 기준으로 썸네일 보정작업 진행하시죠. 작업진행방안은 별도로 코멘트 달겠습니다. 최대한 손이 덜 가는 방법으로 해보죠.

**Comment by bigapple01** [comment]
메뉴명 정리(?)도 필요하지 않을까요?

**Comment by hkjinlee** [comment]
@bigapple01 필요하다고 봐요. 다만 아까 @jinsueng 님과도 잠깐 의견 나눴는데, 먼저 서비스 런칭부터 한 다음에 데이터 merge하는 형태로 하는게 좀더 현실적이지 않을까 싶은 생각도 있습니다.

전체 메뉴 데이터를 한장의 HTML로 뽑아서 어딘가 올려둘 생각인데, 전체 목록 보면서 팀원들 의견을 모아보죠.

**Comment by jinsueng** [comment]
앱내 메뉴썸네일을 살펴보니 2가지의 이슈가 있는 것 같습니다.
1. 사용하는 이미지 API의 정확성 - 이부분은 네이버외 무료 이미지 API를 검색해봤으나, 한글(한식) 이미지 검색은 현재 사용하고 있는 네이버 이미지 API가 제일 좋네요.
2. 이미지 검색시 쿼리 text 변경 - 오픈되어 있는 형태소 Library를 이용해서 일반명사(NNG)와 고유명사(NNP)를 분리하여, 일반명사만 이미지검색에 이용하는 것이 어떨까요? [eg)매콤소고기칼국수 = 매콤/NNP+소고기/NNG+칼국수/NNG --> '소고기칼국수'만 쿼리에 이용.] Java로 구현된 오픈 Library이 있습니다.  http://www.shineware.co.kr/?page_id=835 @hkjinlee 매니저님 썸네일 크롤링한 부분 github에 올려주시면 제가 한번 적용해볼까요?

**Comment by hkjinlee** [comment]
@jinsueng 사실은 네이버 API에서 다음 API로 갈아탔습니다. 네이버 API의 경우 썸네일 말고 원본(=사이즈 큰) 이미지는 원본 URL 말고 자기네 서버를 경유하는 URL만 주는데, 이 URL이 API 호출시점부터 일정 시간이 지나면 expire되더군요. DB에 이미지 URL을 미리 저장해놓고 서비스하는 우리 같은 서비스에서는 쓰기 힘든 형태.

'매콤'을 제외하는 건 괜찮은데요? 다만 scraper는 Java가 아니라 R로 만들어져 있으니, 포스팅해주신 Java 라이브러리는 [rJava](https://cran.r-project.org/web/packages/rJava/index.html)를 쓰거나, 아니면 전희원 님의 [KoNLP](https://cran.r-project.org/web/packages/rJava/index.html)를 써서 직접 R 안에서 형태소분석을 하는 게 더 나을지도 모르겠습니다.

scraper쪽 소스는 P넷 긁는 로직 빼고(여기에 제 로그인 쿠키가 하드코딩으로 들어있음) 오늘 밤에 별도 프로젝트로 커밋해둘께요.

**Comment by hkjinlee** [comment]
팀원 여러분!

https://docs.google.com/spreadsheets/d/17BS_HH-P059K1IHzFRj3aKa6T12Cn_hu1aVEHWTJhN8/edit?usp=sharing 에 현재 메뉴 이름과 이미지 올려두었습니다.

당장 "(뚝)날치알밥" 같은 경우 "(뚝)"은 없애야겠다는 생각이 드는데요, 한번 보시고 의견 주세요.

**Comment by hkjinlee** [comment]
헐! "계란후라이"와 "계란후라이 "(뒤에 스페이스 있음)도 있군요!

**Comment by hkjinlee** [comment]
​메뉴명 정리 로직 commit해두었습니다. 상세 로직은 [여기](https://github.com/bobplanet/Bobplanet-scraper/blob/ae280c9e39e42f515ae6cbd8a7d7dc4e4a923f47/lib/nameCleanser.R)를 확인하시면 됩니다.

그리고, 썸네일 정리 못하신 분들 @bigapple01 @sjs1178 @dusskapark @jhh7984 께서는 바쁘시겠지만 내일 점심 전까지는 완료 부탁드려요. 변경된 메뉴명을 실제 데이터에 반영할 때 썸네일도 함께 반영해야 일이 적어집니다.

**Comment by dusskapark** [comment]
Docs에 있는 이미지를 제일 괜찮은 이미지만 남기고 삭제를 하면 될까요?

2015년 11월 7일 (토) 오후 4:44, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
맞습니다. 필터 해제하면 맨 윗줄에 instruction 있음. 끝나면 노티 부탁해요 :)
2015. 11. 7. 오후 8:34에 "Jude Park" notifications@github.com님이 작성:

**Comment by sjs1178** [comment]
material design 가이드에 따라 color palette 설정 & BI 및 icon 작업 & 메인/드로어 이미지 가이드 잡아보았습니다.

https://ovenapp.io/project/FJfNxVz753MNai0wT3MYuKge9ek5FtY1#9wwXO

위 링크에서 확인가능하며, 공유비번은 1qazxsw2 입니다.

**Comment by hkjinlee** [comment]
다들 바쁘시죠? 데이터 정리 더이상 미루기 어렵습니다. 메뉴데이터가 있어야 평가 및 코멘트기능 추가가 가능한데, 메뉴데이터 정리를 못하고 있어 코멘트 테스트에 다소간 제약이 있어요. 다들 마무리하시고 댓글 등으로 노티 주세요~

**Comment by dusskapark** [comment]
제 파트는 완료했습니다.

**Comment by bigapple01** [comment]
일요일에 끝냈습니다.

**Comment by jinsueng** [comment]
저도 저번주에 완료하였습니다 :)

**Comment by hoyoonjung** [comment]
저도 지난주에 끝냈습니다!

**Comment by hkjinlee** [comment]
@jhh7984 응답 없으시니 제가 해버립니다. 멤버에서 빼버려야지... :)

**Comment by jhh7984** [comment]
늦었네요. 죄송합니다. 일단,헌규M께서 셀렉작업은 하셨길래, 검토후에 일부 누락분과 수정할 이미지 체크해서 링크 add/modify 했습니다. (N열에 '수정'으로 표기). 그리고 하는김에 다른분들담당분량에서도 이미지 링크가 비어있던 null (0) 셀에 대해서도 이미지 검색해서 링크 add 했습니다. (마찬가지로 N열에 '수정'으로 표기)

**Comment by hkjinlee** [comment]
작업내용 서버에 반영 시작했습니다. 1시간 안으로는 작업 끝날 듯.

**Comment by hkjinlee** [comment]
대충 완료. 아직 19개 메뉴는 적합한 이미지가 없네요.

**Comment by hkjinlee** [comment]
지난 주말에 죽여놨던 배치 돌려서 이번주 메뉴데이터도 업데이트 완료. 이슈 클로징합니다.
