### ISSUE TITLE
Google Play 를 통한 Alpha rollout 기능 추가

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#41]
드랍박스를 통해서 APK를 배포하는 것이 보다는 Playstore를 통해서 진행하는 것이 낫다고 생각됩니다. 

> 이 길에 알파테스트와 베타테스트 기능을 체험해보면 좋을 것 같습니다.
- 알파테스트 : 프로젝트 맴버들이 테스트 
- 베타테스트 : 스토어 서비스/사업팀 구성원 위주로 테스트
- 롤아웃 : 공식 출시 

괜찮다고 생각하시면, 퍼블릭키로 사이닝을 해서 전달을 해주시면 제가 등록하겠습니다.

**Comment by dusskapark** [comment]
APK 파일의 알파테스트 배포는 기능이 정말 강력하네요..
아이콘 등은 AB테스트를 해볼 수도 있을 것 같습니다. 

> 아우.. 잘만들었네요..덜덜..

![screen shot 2015-11-10 at 1 32 37 am](https://cloud.githubusercontent.com/assets/4177529/11039475/325e91b0-874b-11e5-8e9a-fa232ada38b9.png)
![screen shot 2015-11-10 at 1 33 40 am](https://cloud.githubusercontent.com/assets/4177529/11039474/325e5d62-874b-11e5-89e5-2b44619813da.png)

**Comment by hkjinlee** [comment]
알파테스트 등록은 해놨습니다. @dusskapark 님께 관리권한 드렸으니 잘해보세요 :)

**Comment by dusskapark** [comment]
@hkjinlee 매니저님, @bigapple01 매니저님께도 권한을 부여해주시기 바랍니다 ^^ (상품 설명 등을 만들어야 해서요 ^^)

**Comment by hkjinlee** [comment]
권한부여드렸습니다. 그런데 권한이 문제가 아니라 실제 아이콘이나 스크린샷 같은 리소스가 문제겠는데요? 어디 공용 드랍박스 같은걸 하나 만들어야 할 것 같음.

**Comment by hkjinlee** [comment]
알파버전 업로드 완료. 앞으로 몇 시간 안에 아래 URL에서 받아볼 수 있을 겁니다.
https://play.google.com/apps/testing/kr.bobplanet.android

**Comment by dusskapark** [comment]
수고하셨습니다^^

2015년 11월 15일 (일) 오후 6:57, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
운동하고 왔더니 떴네요. 다들 위 주소에 접속해서 APK 받으시면 됩니다.
![2015-11-15 8 21 23](https://cloud.githubusercontent.com/assets/7744953/11168550/8bc663a6-8bd6-11e5-8f41-f35cf1fe41a8.png)
