### ISSUE TITLE
Bob플래닛 GA계정에 권한 추가를 부탁드립니다.

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#43]
- Behaviors > experiments 를 추가하고자 하는데, 권한이 없습니다. 
- [구글애널리틱스_콘텐츠실험설정_가이드.pdf](https://github.com/bobplanet/Bobplanet/files/29503/_._.pdf)

**Comment by hkjinlee** [comment]
권한설정 완료
