### ISSUE TITLE
웹사이트 드립 추가 

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#45]
웹사이트에 필요한 드립을 올려주세요. 

> 개인정보 취급방침
> 당신의 정치성향이나 성적취향은 수집하지 않으나 식사 취향이나 영양상태는 수집될 '수' 있습니다.

**Comment by bigapple01** [comment]
일하다가 한 번! 엘베타기 전에 또 한 번!

**Comment by bigapple01** [comment]
밥플래닛이 오늘의 식단을 보내주기 전에는, 그는 다만 하나의 꼬치우동에 지나지 않았다. (꼬치우동 RIP)

**Comment by bigapple01** [comment]
10층 식당 앞에 선 후에야 '아뿔싸! 이건 좀 그렇네!'라며 매점과 편의점으로 발을 돌려본 적이 있으신가요? 이젠 미리미리 확인하시고 당신의 귀한 시간을 아끼세요.

**Comment by bigapple01** [comment]
말하지 않아도 알아요...라니, 세상에 그런 거 없습니다. 당신의 소중한 의견을 '눌러'주세요. 당신의 메뉴 평가가 후니드에 전달됩니다.

**Comment by dusskapark** [comment]
우어.. 푸시가 밀려온닼ㅋㅋㅋ

2015년 11월 12일 (목) 오후 5:54, bigapple01 notifications@github.com님이 작성:

**Comment by bigapple01** [comment]
"맛없는 메뉴를 먹으면 혼이 비정상"

**Comment by bigapple01** [comment]
"메뉴를 미리 보면 그런 기운이 온다"

**Comment by bigapple01** [comment]
I. BOB. U
밥과 나의 연결고리. BOBPlanet.

나머지는 10층에서 먹어가며 영감을 얻어보겠읍니다...
