### ISSUE TITLE
회식 일정 공지

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#47]
- 2015년 11월 17일 저녁 
- 강씨네 오리고기 (판교점)

**Comment by hkjinlee** [comment]
아.. 밖에서 먹는 건가요? 왠지 런칭파티라고 3층 회의실 하나 잡아놓고 치맥 먹으면서 런칭하는 이미지를 상상했었는데 말이죠 :)

**Comment by dusskapark** [comment]
밖에서 먹는 것이 낫잖을까.. 해서요.
점심과 저녁을 모두 같이 먹는 것으로 생각하시면 될 것 같습니다 ^^;
아니면 맥주콜 같은 곳을 가서 밥은 피자를 시키고, 맥주를 빨까요?

2015년 11월 12일 (목) 오후 11:47, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by dusskapark** [comment]
잘 먹고 마셨습니다 :)

![img_0765](https://cloud.githubusercontent.com/assets/4177529/11235123/eee76330-8e11-11e5-9e42-093ec55dd8ae.JPG)
