### ISSUE TITLE
웹사이트 버그모음 

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#49]
![screen shot 2015-11-12 at 7 51 19 pm](https://cloud.githubusercontent.com/assets/4177529/11116581/de46171e-8976-11e5-9e09-5898c223708d.png)
- 웹사이트 코드를 클론하면 계속해서 밥플래닛 소개 md 파일이 뜨는 중;;

**Comment by dusskapark** [comment]
@DoosikKim 매니저님, 동일한 문제가 혹시 발생하나요?

**Comment by hkjinlee** [comment]
@dusskapark 님께는 금요일에 말씀드렸지만 한글파일명의 유니코드 이슈 때문에 생긴 문제입니다. 처음에 '밥플래닛 소개' 파일을 제가 커밋했는데, 어떤 이유에선지 나중에 @dusskapark 님이 'ㅂㅏㅂㅍㅡㄹㄹㅐㄴㅣㅅ' 파일을 커밋하시게 됐더군요. 이건 OS/X에서의 한글 유니코드 presentation 이슈임.
