### ISSUE TITLE
홈페이지에 '개인정보취급방침' 추가

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#50]
개인정보취급방침 페이지 하나 추가해 둡시다.
내용은 대략 이렇게 해주시면 됨:

밥플래닛 개인정보취급방침
## 수집하는 개인정보
- 밥플래닛 앱은 최초실행시 난수 UUID를 생성하여 이용자의 기기 식별자로 삼습니다. 이 UUID는 난수로 생성되므로, 이 자체만으로는 이용자에 대해 아무 것도 알 수 없습니다.
- 메뉴 평가 등 로그인이 필요한 기능을 이용하시려는 이용자에 대해서는 또다른 UUID를 생성하여 이용자의 회원 식별자로 삼습니다. 이 UUID 역시 난수로 생성되므로, 이 자체만으로는 이용자에 대해 아무 것도 알 수 없습니다.
- 이용자께서는 구글ID, 페이스북ID, 네이버ID를 이용해 밥플래닛에 로그인하실 수 있습니다. 이 때, 밥플래닛이 수집하는 개인정보는 다음과 같습니다: 각 서비스의 내부회원번호 / 이용자의 닉네임 / 이용자 프로필 이미지(있을 경우) / 이용자 이메일주소(있을 경우)
## 수집한 개인정보의 이용
- 밥플래닛은 서비스 이용 및 이용자 관리 등 아래의 목적으로만 개인정보를 이용합니다.
- (작성중)
## 개인정보의 위탁 및 제공
- 밥플래닛은 밥플래닛 팀 외부로 어떠한 개인정보도 위탁 혹은 공유하지 않습니다.
## 개인정보의 파기
- (작성중)
## 개인정보 관리책임자 및 담당자
- 밥플래닛 팀: bobplanet.team@gmail.com

**Comment by dusskapark** [comment]
블로그 쪽에 작성을 하도록 하겠습니다.

**Comment by hkjinlee** [comment]
블로그로 따면 URL이 http://bobplanet.kr/blog/2015-11-13 이런 식으로 나오게 되니 페이지를 하나 따로 따주시면 좋겠습니다. http://bobplanet.kr/privacy/ 가 되도록이요.

**Comment by hkjinlee** [comment]
일단 개발 완료. 본문은 향후 업데이트하기로 함.
