### ISSUE TITLE
API 확인 가능한 주소 

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#51]
안녕하세요. 

기존에 확인 가능하던 API 주소가 현재는 작동하지 않는 것 같아서 일감을 등록합니다.
- [기존 API확인 url](https://apis-explorer.appspot.com/apis-explorer/?base=https://1-dot-kr-bobplanet.appspot.com/_ah/api#s/bobplanetApi/v1/)

> 길에 API가 필요한 @DoosikKim , @박양제 매니저도 확인해주세요..

**Comment by hkjinlee** [comment]
API Explorer가 동작하지 않는건가요? 아니면 API를 호출의 결과값이 이상한가요?

**Comment by dusskapark** [comment]
Explorer 제대로 동작하지 않습니다. 접속하면 API목록 페이지로 이동하지 않습니다. ㅠ

2015년 11월 13일 (금) 오후 3:31, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
구글이 API explorer 도메인을 바꿨던데(developer.google.com 아래로) 그 영향인 듯하네요.
방법 찾아볼께요!

**Comment by hkjinlee** [comment]
구글 버그인 듯? 지금 다시 아래 주소로 접속해보세요.
https://apis-explorer.appspot.com/apis-explorer/?base=https://1-dot-kr-bobplanet.appspot.com/_ah/api#s/bobplanetApi/v1/

**Comment by dusskapark** [comment]
헉.. 다시 정상적으로 나옵니다..

2015년 11월 13일 (금) 오후 5:01, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
클로징합니다
