### ISSUE TITLE
GA 데이터 점검

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#52]
점검포인트
- 앱
  - 화면이벤트: Activity, Fragment, Dialog => 이름이 너무 길다. 앞쪽 패키지 이름 제거 필요 => 완료.
  - 로그인이벤트
  - 동작속도: 데이터 올라오지 않고 있음. 확인 필요. => 수정 완료. label은 옵션이고 variable이 필수였음
  - 구글플레이 연결: 완료
- 웹
- 앱 > 웹
  - 잠시 사라져있던 사용자 추적코드 반영 완료

**Comment by dusskapark** [comment]
내일 한번 모여서 리뷰를 하면 좋을 것 같습니다.
비슷하게 페이스북 픽셀을 웹에 적용하는 것도 내일까지 진행하겠습니다.

2015년 11월 15일 (일) 오전 9:35, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
@jinsueng 빠진내용은 없는지 한번 봐주세요. 특별히 잘못된 게 없으면 이슈 클로징하시면 됩니다.

**Comment by jinsueng** [comment]
화면 데이터는 확인하였고, 로그인 이벤트는 이미 제가 소셜 로그인하여서 별도 확인 못하였습니다.
웹은 오픈이후에 이벤트 추가해야 될것으로 판단되네요.
오픈이후에 개선점 다시 issue생성하겠습니다. 감사합니다~
