### ISSUE TITLE
웹페이지 CSS 조정

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#54]
H1이 너무 크네요. CSS 도입이 굉장히 많은 손을 요하는 건 알고 있지만, 빨리 손봐주셔야 할 듯.
![screenshot_2015-11-15-11-22-33](https://cloud.githubusercontent.com/assets/7744953/11166823/4cc8f060-8b8b-11e5-87eb-97771cb8a196.png)

**Comment by dusskapark** [comment]
![screen shot 2015-11-16 at 2 31 02 am](https://cloud.githubusercontent.com/assets/4177529/11169979/20a6cea6-8c0a-11e5-9616-a5353208a53d.png)

디자인에 재능이 없다는 것을 느끼는 주말이었습니다..
디자인이 매우매우 마음에 안들지만.. 일단은 수정을 했습니다.
차차.. 개선해보겠습니다.

**Comment by hkjinlee** [comment]
커밋로그 보니 Disqus도 다셨네요? 정말 고생 많으셨음!

**Comment by dusskapark** [comment]
버전 2.0에서는 디자인도 좀 손을 봤으면 합니다. ㅠ

2015년 11월 16일 (월) 오전 7:35, Jin, Heonkyu notifications@github.com님이 작성:
