### ISSUE TITLE
페이스북 픽셀 적용

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#56]
냉무

**Comment by raphael-shin** [comment]
와 픽셀까지 적용을!

**Comment by dusskapark** [comment]
아직 액션을 어떤 것을 해야할지 몰라서 정의를 못하고 있습니다. 일단은 다운로드 웹페이지에 적용을 해볼까 하는 중입니다.

2015년 11월 19일 (목) 오후 2:32, Jungseob Shin notifications@github.com님이 작성:

**Comment by bigapple01** [comment]
@dusskapark 특정 액션에 픽셀 다는 법 혹시 찾으셨습니까...? (엉엉)

**Comment by dusskapark** [comment]
https://developers.facebook.com/docs/facebook-pixel/api-reference

자바스크립트 액션으로 픽셀을 설정할 수 있을 것 같습니다.
뱅기에서 처리해보겠습니다.

**Comment by dusskapark** [comment]
금일 수정해서 적용했습니다.
