### ISSUE TITLE
베타버전 런칭 준비

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#60]
오늘 저녁에 회식하면서 아래 역할을 어떻게 나누어맡을지 얘기해보시죠.
- 블로그 저널리스트
- 후니드 채널: 인터뷰도 담당
- 스토어 앱관리자
- 비콘 품질 관리자

**Comment by hkjinlee** [comment]
저녁 회식시간에 정해진 각자의 역할을 알려드립니다:

블로그 저널리스트&홈페이지 관리: @bigapple01 
스토어 앱관리: @hoyoonjung 
비콘 품질 관리&데이터분석: @jinsueng 
후니드채널&이벤트기획: @jhh7984 
마케팅&디자인(동영상/이미지포함): @sjs1178 
iOS개발: @DoosikKim 
홈페이지개발: @dusskapark 
앱개발: @hkjinlee

그리고 프로젝트 외연확장 및 앱스토어 개발자회비 충당을 위해 추가멤버를 모집하기로 했습니다. 각자 한명씩 모셔오기로.

**Comment by dusskapark** [comment]
iOS 프로젝트를 하나 새로 파야할 것 같습니다. 

최은지 매니저(@happifyus )가 팀원으로 합류 했습니다.

**Comment by hkjinlee** [comment]
방금 베타버전 구글플레이에 올렸습니다. 오픈베타로 되어있고, 아래 URL에 접속해서 '테스트신청'을 해주시면 그 뒤부터는 구글플레이에서 일반 앱과 동일하게 설치/업그레이드 가능.
https://play.google.com/apps/testing/kr.bobplanet.android

오늘밤에 drawer menu까지 구현해서 T스토어 검증요청 들어갈 예정.

**Comment by dusskapark** [comment]
우선검증으로 준비를 할까요?

2015년 11월 18일 (수) 오후 6:37, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
아뇨 뭐 우선검증까지. 오늘 밤에 개발을 끝낼 수 있을지 없을지도 아직 모름

**Comment by hkjinlee** [comment]
- 신규버전 1차 개발완료: DrawerMenu 추가함. 아직 로그인한 사용자 identity를 보여주는 기능은 없음
- 해당 바이너리 국을놀이장터 베타등록 및 T장터 검증요청 완료함

**Comment by hkjinlee** [comment]
T스토어 검증반려 먹었습니다. 이슈 재오픈함.

**Comment by hkjinlee** [comment]
검증반려사유가 정확하네요. 검증팀 고생많으시네요.
- 검증반려사유: DrawerMenu에서 '오픈소스라이선스'를 누르면 '개인정보취급방침'이 뜸
  (실제로 그렇습니다. 음주코딩의 한계...)

오늘 수정해서 재검증요청 들어갑니다
