### ISSUE TITLE
facebook open graph가 잘 작동하지 않는 문제

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#62]
> 테스트 사이트: https://developers.facebook.com/tools/debug/og/object/

메인페이지는 그나마 작동은 하는데, 
블로그 페이지 등은 아예 동작을 하지 않네요. 
http://bobplanet.kr/blog/2015/11/17/beta-feedback.html

무엇이 문제일지는 한번 찾아봐야할 것 같습니다.

**Comment by dusskapark** [comment]
@jungseob86 매니저님

open graph가 잘 작동하지 않는 문제가 좀 있습니다.
예를 들어 http://bobplanet.kr/2015/11/19/bobplanet-introduction.html 이 블로그 게시물의 경우는 og태그가 잘 들어가 있는데, facebook의 url debugger 에서 정상동작을 하지 않는 문제가 있네요. 왠지 매니저님이 젤 잘알꺼 같아서.. 질문을 올립니다 ㅠ

**Comment by raphael-shin** [comment]
@dusskapark og태그의 image URL에 `http://` 를 넣어보세요. 그리고 제가 알기로는 url 태그도 넣어야지 잘 동작하는걸로 알고있습니다.

**Comment by dusskapark** [comment]
음.. 잘 들어가 있습니다; 근데 잘 안되네요 ㅠ
http://bobplanet.kr/blog/2015/11/17/beta-feedback.html

**Comment by raphael-shin** [comment]
@dusskapark 저도 잘 안되다가 -_-;; 지금 갑자기 디버거에서 잘 나오네요. 확인 부탁드려요. 가끔 페이스북 봇이 잘 동작 안하더라구요. 버그가 있나봅니다.

```
Meta Tag    <meta property="og:url" content="http://bobplanet.kr/blog/2015/11/17/beta-feedback.html" />
Meta Tag    <meta property="og:title" content="&#xbca0;&#xd0c0;&#xbc84;&#xc804;&#xc5d0; &#xb300;&#xd55c; &#xac1c;&#xc120;&#xc758;&#xacac;&#xc744; &#xc62c;&#xb824;&#xc8fc;&#xc138;&#xc694;" />
Meta Tag    <meta property="og:description" content="&#xbc25;&#xd50c;&#xb798;&#xb2db; &#xd300;, &#xc2dd;&#xc131;&#xc0c1;&#xb2e8;(&#x98df;&#x661f;&#x5546;&#x5718;)&#xc5d0;&#xc11c; &#xbb38;&#xc548;&#xc778;&#xc0ac; &#xb... See More
Meta Tag    <meta property="og:type" content="article" />
Meta Tag    <meta property="og:image" content="http://bobplanet.kr/assets/images/step4_facebook.png" />
```

**Comment by dusskapark** [comment]
블로그 포스트마다 되는 것이 있고 안되는 것이 있습니다;; 뭐지 ㅎㅎ;;;;;

2015년 11월 20일 (금) 오후 4:11, Jungseob Shin notifications@github.com님이 작성:

**Comment by dusskapark** [comment]
정상 작동 확인했습니다 ^^
