### ISSUE TITLE
제품 개선을 위해서 PR 시스템을 제안합니다.

### ISSUE THREAD

**Issue by raphael-shin** [bobplanet/Bobplanet#63]
`Pull Request` 방식은 GitHub의 강력한 기능입니다.
실제 Open Source 프로젝트 진행처럼 Pull Request 로 소스코드 개선(수정)을 하는 방향은 어떤지요?

**Comment by raphael-shin** [comment]
예시로 https://github.com/bobplanet/Bobplanet/pull/64 하나 PR 했습니다.

**Comment by hkjinlee** [comment]
@jungseob86 님 반갑습니다 :)
PR을 쓰지않을 이유가 하나도 없지요. 다만 commit log 보면 아시겠지만 지금까지 개발은 사실상 저 혼자의 job이고, 따라서 굳이 PR까지 써야겠다는 생각이 들지 않은 것 뿐입니다. 

사실 안드로이드 개발도 처음, Github 사용도 사실상 처음이라 잘 몰라서 그런 것도 있습니다. PR을 날려본적은 있지만 merge해본 적은 없으니 '미지의 것'에 대한 두려움이 없다고 하면 거짓말이겠죠.

어쨌든, 첫 PR 감사드립니다. 내용 훑어보고 바로 merge할께요.

**Comment by raphael-shin** [comment]
@hkjinlee 재밌는 프로젝트인 것 같습니다 :)
혼자서 개발하고 있으셨다니 정말 대단하세요!

**Comment by dusskapark** [comment]
@jungseob86 이 프로젝트에 합류했습니다. 

@hkjinlee 매니저님, 잡포지션 하나 끌올... 해야할 것 같습니다. ^^

**Comment by raphael-shin** [comment]
@hkjinlee PR을 다시 날리려고 합니다. 제가 실수한게 있네요. 브랜치를 안따고 바로 master 에서 PR을 날렸습니다; 일단, 이슈 종료하고 PR 다시 날리겠습니다.

**Comment by hkjinlee** [comment]
PR 날려주실 때 gitignore 안에 secrets.properties가 빠지지 않게 해주세요 :) 외부에 공개되면 조금 곤란한 API키 등의 내용을 담고 있는 파일입니다.

**Comment by raphael-shin** [comment]
@hkjinlee 네 알겠습니다 :)
