### ISSUE TITLE
NFC 스티커 제작/부착에 대하여

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#66]
11번가에서 주문한 NFC 스티커가 왔습니다. 바로 이 제품:
http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=1146897558

10층 식당 출구 TV 앞 테이블에 NFC 스티커를 붙여두고 각각 T스토어, 구글플레이스토어 다운로드 링크를 넣어서 사우들이 손쉽게 앱을 설치할 수 있도록 할 생각인데.. 이거 해보실 분?

업무연관도를 보면 @jhh7984 님이나 @jinsueng 님이 맡아주시면 좋겠네요.

**Comment by jinsueng** [comment]
@hkjinlee 라즈베리파이 식당에 설치 및 테스트시, 제가 같이 진행하도록 하겠습니다 :) 그런데 라즈베리파이는 세팅 완료되었는지요?

**Comment by hkjinlee** [comment]
@jinsueng @jhh7984 그럼 다음주 초에 같이 가시죠. 어제 10층에 저녁먹으러 갔다가 영양사님께 여쭤봤더니, 점장님이 오늘까지 휴가라고 하시더군요. 차주초에 저한테 연락을 주기로 했어요.

그리고 비콘 쪽은 라즈베리파이 한대 더 주문했고, 유효거리 80m짜리 블루투스 동글도 오늘 주문 완료. 다음주에 두 대로 테스트해보면 됩니다. 안에 올라가는 소프트웨어는 특별히 손 볼 게 없음.

**Comment by jhh7984** [comment]
@hkjinlee @jinsueng 월요일까지 인터뷰 자료(Questionare)작성하도록 하겠습니다. 
같이 가서 한방에 다 끝낼수도 있겠네요...참고로, 점장님 위주로 인터뷰하고, 시간되면 영양사님정도도 한분 추가 인터뷰 하면 좋을 듯 합니다. (같은 분이려나요)..자료는 설문+영상촬영 정도로 할께요.

**Comment by hkjinlee** [comment]
앞으로 @jhh7984 님이 자주 뵈어야 할 분이니 꽃단장하고 오세요 ㅋㅋ
참고로 점장님과 영양사님은 다른 사람입니다 :)

**Comment by hkjinlee** [comment]
방금 NFC 스티커 제작했습니다. 프로그램 쓰니까 그냥 되네요. 다음 화요일 점심때 보여드리지요 :)
