### ISSUE TITLE
T스토어 다운로드 링크 추가

### ISSUE THREAD

**Issue by bigapple01** [bobplanet/Bobplanet#69]
@dusskapark 매니저님, 구글플레이 다운로드 링크처럼 T스토어 다운로드 링크도 넣어야 하지 않을까요? 위치는 하단 구플 로고 아래에 + 상단에도 추가하는 게 좋...겠죠?

**Comment by dusskapark** [comment]
> 직접 분기처리 다운로드 페이지를 만들어 볼까.. 했는데; 
> 잘 작동하지 않아서.. 일단은 포기했습니다. ㅠ 

@진헌규 매니저님, 

밥 플래닛 메인으로 가는 uri scheme 이 있으면 skpla.net으로 처리를 할 수 있을 것 같습니다.

> bobplanet://daily/main 이런식으로..

![screen shot 2015-11-21 at 4 00 26 am](https://cloud.githubusercontent.com/assets/4177529/11308971/7a568af6-9004-11e5-901c-bd97de9b14e0.png)

**Comment by dusskapark** [comment]
@bigapple01 매니저님, 페북 픽셀로 다운로드 이벤트 성과를 추적하려면...
말씀하신 것처럼 다운로드 페이지를 따로 만들어야 할 것 같습니다. (휴가 갔다와서 해보겠습니다; )

**Comment by dusskapark** [comment]
추가했습니다.
