### ISSUE TITLE
평점을 5점 체계에서 '좋아요', '싫어요'로 변경

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#7]
- 5점 체계보다 '좋아요', '싫어요' 형태가 서비스에 더 알맞는 듯.
- 화면상에는 '좋아요 100명, 싫어요 50명' 형태로 display (일단은 '좋아요'를 먼저 보여주자)
- '싫어요'에 대해서는 태그 필수 입력 (태그에 대한 +1 기능 필요)
- 일간 메뉴리스트 화면에서 대표태그 동반노출

**Comment by hkjinlee** [comment]
좋아요 : 싫어요를 상대비중(수평 bar인데 파란색 vs 빨간색)으로 시각화하는 것도 괜찮을 듯.

**Comment by bigapple01** [comment]
유튜브의 좋아요/싫어요 바 말씀이시죠? 그런 느낌이면 될 것 같습니다.

**Comment by hkjinlee** [comment]
이슈는 해당 기능이 제품에 반영되기 전까지는 열어두는게 좀더 맥락에 맞아 보입니다.
일단 부활시킬께요~

**Comment by bigapple01** [comment]
제가 실수로 닫았네요... ㅎㄷㄷ

**Comment by hkjinlee** [comment]
기능구현 완료. (화면은 좀더 이쁘게 만들어야겠지만...)
