### ISSUE TITLE
후니드 정식 인터뷰

### ISSUE THREAD

**Issue by jhh7984** [bobplanet/Bobplanet#70]
- 인터뷰 일정 확정 (11/24, w/점장님 외)
- 인터뷰 예상 질문 (아래)
  ## https://docs.google.com/document/d/137hVsUt8Q6br5ATQYgpQn1MG43T4_L2Xf5QdG6_cAXw/edit?usp=sharing
  
  <후니드 인터뷰  Questionare >
  - 인터뷰 형태의 Question & Answer 중심 (점장, 영양사님 정도)
  - 식단 및 이용환경 개선의 목적에 부합하는 형태의 인터뷰 시행
  - 향후 자료 활용을 고려한 방식으로 진행 (동영상 촬영, Questionare활용)
  - 프로모션과 연계된 협찬을 유도 (식권, 1개월 이용권 등?)

<Q1> 후니드에 대한 소개를 부탁 드립니다.

<Q2> 후니드(SKP) 조직 구성 및 소개 좀 부탁 드려요~

<Q3> 후니드만의 어떤 특징이 있나요? (장,단점 등)

<Q4> 후니드에서 플래닛 사옥만의 특징이 있나요?

<Q5> 플래닛 고객들에 대한 인상, 느낌은?

<Q6>  힘드신 점은? ^^;

<Q7> 플래닛 고객들의 불만이 뭔가요?

<Q8> 플래닛 고객들이 칭찬하는 점은 뭔가요?

<Q9> 후니드에서 서비스 개선을 위해 노력했던 점들은? (홍보겸)

<Q10> 위의  결과는 어땠나요? 또는 그 후기는…?

<Q11> 저희와 같은 서비스가 있다면 바라는 점은? (구체적)

<Q12>  저희 서비스와 서로 함께 협력 해봤으면 하는 부분은?
공동 프로모션
타사 식당 벤치마킹 (NC soft의 월1회 뷔페식 등) 
식당 대기 분석 / 메뉴 분석 / 호불호 분석 등

<Q13> 끝으로, 플래닛 구성원 분들께 하고 싶은 말씀 한마디~

[ 추가 질문]

<+a> A코너와 B코너의 차이점은?

<+a> 해장메뉴는 주로 언제? 제일 인기있는 해장메뉴는?

<+a> 식당 이용 팁은? (언제 사람이 제일 적더라..반찬은 주로 언제 바뀐다.. 등)

<+a> 영양사님 점장님 추천 메뉴는? 

<+a> 기타 여담 (ㅇ 메뉴는 싫다는 사람이 많지만 건강을 위해 꼭 식단에 반영한다. A,B코스 반찬좀 둘다 가져가지마라..등)

**Comment by hkjinlee** [comment]
내일 점심때 Plalab 끝나면 10층 올라가서 1시반부터 2시까지 비콘 테스트좀 하고, 2시부터 인터뷰 진행하면 되겠네요 :)

**Comment by dskim98** [comment]
가장 단가 비싼메뉴 vs 가장 단가 저렴한 메뉴

**Comment by jinsueng** [comment]
## 후반기 인터뷰 내용 업데이트 합니다.

플래닛의 특징
- 스크린 만족도 테스트 : 반복적으로 누르는 사람이 있음. 그러나 시간이 지나면서 데이터가 쌓이면서, 객관화된 고객의 의견이 되었음. 
- 플래닛 평균 60점 후반대, 티타워가 평균 85점 
- 텔레콤 계열은 직원들에게 식대를 주고 자율적으로 선택하게 하기때문에, 식수예측이 매우 중요함. 

잘나가는 메뉴 / 만족도 좋은 메뉴 
- 돈까스, 육개장, 북어국, 짬뽕, 삼겹살 데리야끼 덮밥
  만족도가 안좋은 메뉴 
- 비빔면 : 2달전 본사에서 야심차게 추천한 메뉴였지만, 망했음

점심보다 저녁에는 만족도가 더 좋음.
A,B의 메뉴는 비슷하게 나가고 있음. 

좀 짜면 전체적 만족도는 올라가나, 노트 글 피드백에는 안좋은 의견이 올라옴

본사에서 새로운 메뉴를 1달에 한번씩 가이드 내려옴

실장과 조리장의 co-work이 중요함

위생점검이라 불시로 들어옴. 위생점검시 걸리면 KPI 0점

전국내 후니드 식당이 70개있음. 직원은 2200명
후니드가 식당만이 아니라, 사옥관리, 보안경비도 같이 하고 있음.

날씨, 요일별 식수 예측이 식당에서 진짜 필요한 서비스임.
텔레콤 계열은 식대이지만, 이외 계열은 현물로 거래됨.(식대를 별로 제공안함)
텔레콤 계열은 식수 변동폭이 매우 큼.
외부변수(현대백화점, 옆 건물)이 생기면 식수에 많은 영향을 줌

식당개선
- 식객활동 : 지난 4월에 진행함.

판교 식당 아주머니들은 이직율이 높음. 서울에 비해 급여도 10~15% 높음

**Comment by jhh7984** [comment]
# 전반기 인터뷰 내용 업데이트 합니다.

ㅇ 인터뷰이 : 고종민 팀장님, 최인나 점장님
ㅇ 인터뷰어 : 진헌규,장활훈,이진승M님
ㅇ 주제 : 서비스와의 Collabo. 방안 + 프로모션 협조 요청 + 에필로그, 에피소드 등 
ㅇ 인터뷰 결과 및 총평
    - 팀장님의 서비스 개선의 강한 의지와 바쁘신 점장님 탓에, 저희가 의도한 바의 자료들은 다 얻진 못하것 같네요(점장님의 산뜻한 인사말 영상클립, 웹에 넣을만한 재미난 뒷담화 등). 다만, 식권 40장을 협찬받았고, 인터뷰 내용중 한두개 정도만 필요시 소재로 활용할수는 있을 것 같습니다. 또 함께 사진촬영한번해서 소개자료나 협찬 코너에 게시하는것도 좋을 것 같네요~

**1. 지원 프로모션**
       - 식권 40장 협찬 예정 (20장~50장 심고 끝에)
       - 후니드 주변 비콘 설치 및 포스터 홍보 장소 제공 

**2. 서비스에 바라는 점 등**
       - 수요예측에 도움이 되는 지표 제공 (수요 예측 정확도 제고가 무엇보다 절실한 상황)
       - 평점 등 식단개선에 도움이 되는 데이터 전달 요청
       - 너무 적나라한 비판의 장이 되질 않기를 우려/ 환경 조성 요청 

**3. 에필로그.에피소드용 소재**
**3.1)플래닛 후니드 소개**
        - 플래닛은 현재 22명이 담당하시며, 점장1, 영양사2, 조리장1, 주방 아주머니 분들이 열심히 일하시는중 (1사옥은 16분이 담당하신다고 함)
       - 대부분의 멤버는 2년이상 현재 플래닛을 줄곧 담당하셨으며, 노하우와 열의로 업무에 임하고 계심
       - 위처럼 중식대보조형태의 지점이 몇안되기 때문에, 나름 외부 식당들과의 경쟁을 위해 많은 고민과 환경 개선에 힘을 쏟고 있다고 함 (텔레콤 계열만)
       - 조리장님은 한식과 중식에 일가견(?)이 있으시다고 함
**3.2) 후기나 에피소드**
        - 분식,까페,식당(A,B), 2사옥으로 신경쓸 요소가 많아 플래닛 후니드가 애로사항이 많은 편이라 함
           (이해도 제고와 함께,,,모든 만족을 다 충족 시킬수 없음을 양해~)
        - 식당(A,B) 메뉴는 집밥처럼 조미료를 최소화하고, 신선한 야채를 당일 조리하는것을 원칙으로 함
        - 식후 평점은 좋은데, 너무 짜다..라는 평도 동시에 있는 등의 식단개선에 애로사항이 있다.
        - 밥을 싸오셔서 공짜 미역국과 김치를 드시는분 / A,B코너 반찬을 다 쓸어가시는 분들땜에 애로사항이 있음 (비용외에도 수급 조절의 문제)
        -  노트와 후기는 정성껏 챙겨보고 있으며, 내부 영양사님 조리장님이 개선활동에 반영하고 있음
        - "냉장고를 부탁해" 같은 프로젝트를 해보려했으나, 여러가지 사정으로 진행 홀딩?불가?
        - "식객" 프로젝트도 위처럼 식단개선의 취지에서 열의를 가지고 시행했었음

**Comment by jhh7984** [comment]
# <프로모션 안> 입니다. 의견주세요

*\* “밥플래닛” 앱 런칭 기념 프로모션**

1) 기간 : 12/8~12/18 (런칭후 10일)
2) 참가 방법 : 앱을 다운(아래 참조)하여 식사후에 식단을 평가
3) 포상
         3.1) 최다 참여상 (식단 평가 열심히 참여하신분들중) - 10명 \* 식권 1매
           → 현재 abusing 가능? 다운로드상? (매번 10번째 다운로드 유져분) - 10명 \* 식권 1매
         3.2) 최고 평가상 (식단 평가후기를 남기신분들중) - 10명 \* 식권 1매
         3.3) 최고 의견상 (서비스 개선의견을 주신분들중)  - 10명 \* 식권 1매
         3.4) 대상 (위의 분들중에 독보적이신 분) - 1명 \* 식권 10매 + 10만원이하의 깜짝 경품
4) 전달 방법 : 이벤트 종료후 7일내에 개별 메일 통보 (facebook 로그인시? 로그아웃 메뉴 필요?)
