### ISSUE TITLE
GA 패러미터 정의

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#73]
런칭 프로모션에 대한 GA 패러미터는 이렇게 할까 합니다. 의견 부탁!
- utm_medium: 트래픽을 유도하는 매체의 타잎을 정의
  - ad: 광고 타잎
  - site: 사이트 타잎. http://bobplanet.kr 및 페이스북 페이지 등
  - store: 앱스토어 타잎
  - offline: 포스터 등 오프라인 venue 타잎
- utm_source: 트래픽을 직접 보낸 소스를 정의
  - google: 구글. 구글광고 및 구글플레이스토어 등에 사용
  - facebook: 페북 페이지 및 페북 광고에 사용
  - pnet: 우리들 이야기
  - blind: 블라인드
  - tstore: T스토어
  - frontgate: 식당 정문 포스터
  - reargate: 식당 후문 NFC 스티커
- utm_campaign: 특정 프로모션의 식별자
  - launch_201512: 런칭 프로모션

**Comment by hkjinlee** [comment]
이번 프로모션 케이스:

우리들 이야기: utm_medium=site&utm_source=pnet&utm_campaign=launch_201512
블라인드: utm_medium=site&utm_source=blind&utm_campaign=launch_201512
페북광고: utm_medium=ad&utm_source=facebook&utm_campaign=launch_201512
구글광고: utm_medium=ad&utm_source=google&utm_campaign=launch_201512
정문스티커: utm_medium=offline&utm_source=cafeteria_front&utm_campaign=launch_201512
후문스티커: utm_medium=offline&utm_source=cafeteria_rear&utm_campaign=launch_201512

**Comment by hkjinlee** [comment]
URL shortener를 이용해서 URL을 줄이는게 좋겠는데, skpla.net은 P넷 계정으로 연동돼서 여러 사람 사이에 데이터 공유가 불가능하니 뭔가 대안이 있으면 좋겠네요.

**Comment by dusskapark** [comment]
자바스크립트 페이지를 따로 만드는 것이 좋을 것으로 생각되는데... 당장은 방법이 없으니, 구글 플레이 링크와 티스토어 링크를 따로 만들겠습니다. 

그리고 메인페이지에서 다운로드 버튼을 누르는 경우도 있으니 아래와 같은 구분을 추가하겠습니다. 
메인페이지: utm_medium=site&utm_source=main&utm_campaign=PartBadge

**Comment by hkjinlee** [comment]
앞으로 자주 쓸 듯하니 별도 [위키페이지](https://github.com/bobplanet/Bobplanet/wiki/%EB%B0%A5%ED%94%8C%EB%9E%98%EB%8B%9B-%EB%A7%81%ED%81%AC-URL-%EA%B7%9C%EC%B9%99)로 빼고 본 이슈는 클로징합니다
