### ISSUE TITLE
밥플래닛 런칭프로모션 포스터 공유

### ISSUE THREAD

**Issue by sjs1178** [bobplanet/Bobplanet#75]
포스터 안 공유드립니다.

버전은 총 2가지이고, 1)밥플래닛을 사용해야하는 이유 2)출시/설치안내 3)이벤트 안내를 내용으로 했습니다. 버전은 총 2가지이고 첫번째는 보통장소들 + 입구쪽, 두번째는 출구쪽에 부착되면 될 것 같습니다.

(밥플래닛을 사용해야하는 이유를 메인으로 잡다보니 일부 타 서비스를 까게 되었네요...)

![default](https://cloud.githubusercontent.com/assets/15334249/11580774/2a28367c-9a7e-11e5-9456-51dcda5bab0f.jpg)
![2](https://cloud.githubusercontent.com/assets/15334249/11580775/2a32466c-9a7e-11e5-8e4f-218392570d95.jpg)

**Comment by hkjinlee** [comment]
고생하셨습니다! 역시 PD님 작품답게 고퀄 오브 고퀄이네요. 코멘트 조금 드리자면:
- 저는 1안이 2안보다 좋아 보입니다 :) 1안은 로그인의 번거로움을 "덜어준다"는 코드가 되는데, 2안은 말씀주신대로 "까는" 코드가 되겠네요.
- 앱 설치는 NFC 스티커를 이용합니다. (생각해보니 @sjs1178 님이 참석 못하셨을 때 진행했던 듯) T스토어 URL과 구글플레이 URL을 담고 있는 스티커를 각각 한장씩 만들어 포스터에 붙일 예정이에요. 스티커 사이즈는 3cm \* 3cm의 원형이니, 스티커 붙일 자리를 확보해주시면 되겠습니다. 제 자리에 샘플이 있으니 와서 한번 보시죠.
- Creative는 '침몰' 말고 다른 코드 없을까요? 개인적으로 아직 노란리본 달고 다니는 사람으로, 침몰코드가 살짝 불편하게 여겨집니다. (세월호 생각나요 ㅠㅠ)

**Comment by hkjinlee** [comment]
http://www.shutterstock.com/pic-339975023/stock-vector-the-dismantling-of-the-wall-icon.html?src=Onn_YT3MXnWeSBC4AAunuw-1-11
이런 류는 어때요? (Shutterstock 계정 있으니 유료 구매 가능. 다른 이미지라도 무방)

**Comment by hkjinlee** [comment]
http://www.causematters.com/farmfoodbook/
깨는 형태도 가능은 할 듯. (추천검색어: "no more")

**Comment by hkjinlee** [comment]
마지막. 역시 가장 무난한 건 빨간색 금지 sign이겠네요. PSD도 있음.
http://mauve7.tistory.com/136

**Comment by sjs1178** [comment]
아무 생각없이 물 아이콘 했는데 ㅠㅠ

아래와 같이 수정해봤습니다. 사내인 만큼 세절된 것 같은 느낌을 내봤습니다.
그리고 NFC도 수정해봤는데, 사이즈는 실제 A3로 인쇄해보고 조정해야할 것 같습니다.

![3](https://cloud.githubusercontent.com/assets/15334249/11582150/394a3b54-9a8e-11e5-9438-406b07be9c85.jpg)

**Comment by hkjinlee** [comment]
오오오 세절 괜찮은데요? 역시 PD님의 손길이 닿으면 확 달라지는군요.
NFC 스티커는 두 개 들어가면 됩니다. 참고하시라고 지금 자리로 가져다 드리겠음.

**Comment by dusskapark** [comment]
PhotoFunia 라는 사이트에서 합성을 할 수 있네요. 

![photofunia-1449206498](https://cloud.githubusercontent.com/assets/4177529/11584288/16549ffa-9aa6-11e5-92cc-e42ad4f01f3a.jpg)
![photofunia-1449206609](https://cloud.githubusercontent.com/assets/4177529/11584289/167b8002-9aa6-11e5-82a4-41b160ced18e.jpg)

**Comment by dusskapark** [comment]
스타워즈 컨샙도 시도해봄직.. 해서..이벤트 사이트를 만들었습니다. 
상품으로 CGV 영화티켓주고.. 스타워즈 보라고 하는 것도..;

http://bobplanet.kr/event.html
