### ISSUE TITLE
식당 비콘 설치 

### ISSUE THREAD

**Issue by jinsueng** [bobplanet/Bobplanet#77]
식당 좌측, 우측 구석에 라즈베리파이 비콘 설치 완료하였습니다.

**Comment by jinsueng** [comment]
12/8일 설치 사진
https://goo.gl/photos/Lgub9eKBbpnDQNZz5
https://goo.gl/photos/oE9GiizrNZh3VExX8

Beacon감지 되는것도 확인 완료하였습니다. 식당에서 나가기만 하면 안잡히네요 ㅎ 

issue오픈하자마 close하겠습니다 ㅎ

**Comment by hkjinlee** [comment]
Thumbs up!
