### ISSUE TITLE
A/B 테스트 페이지를 추가했습니다. 

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/Bobplanet#79]
웹에 몇가지 업데이트를 했습니다. 
- 픽셀코드를 다시 적용했습니다. (오타가 있었던 것 같습니다.)
- 오늘의 메뉴를 단독으로 보는 페이지를 추가했습니다. (http://bobplanet.kr/menu.html/)
- A/B 테스트가 가능하도록 type_b 페이지를 만들었습니다. (http://bobplanet.kr/index_type_b.html )

Type B 페이지는 Google Analytics > 실험에서 켜면... 바로 활성화 됩니다.

**Comment by bigapple01** [comment]
메뉴에 아침/점심/저녁을 분간할 수 있는 표식(?)이 있으면 좋겠습니다. :)

**Comment by dusskapark** [comment]
추가했습니다.
