### ISSUE TITLE
아이콘 제작

### ISSUE THREAD

**Issue by hkjinlee** [bobplanet/Bobplanet#9]
- 용처: 앱아이콘 및 GitHub 프로젝트 아이콘
- 포맷: 배경투명한 png
- 레이아웃: 상단에는 "밥"을 한글로 쓰고 하단에 "planet"을 영문으로 배치
- Key Color: #FF5722 / #D84315 / #FFCCBC / #F9A825
- 사이즈: 192x192로 일단 작업

**Comment by dusskapark** [comment]
[드랍박스 링크](https://www.dropbox.com/sh/ake517w291kpceq/AACL-B7xEzRQ6T3hsAsYNE7Na?dl=0)를 추가합니다.
- 주문제작품: ![dohyun001](https://cloud.githubusercontent.com/assets/4177529/10625673/d8e2238c-77e0-11e5-9b80-d61a27a73bd2.png)

**Comment by dusskapark** [comment]
아이클라우드 링크를 다시 보냅니다.
링크가 동작하면 드랍박스 링크는 삭제하겠습니다.

https://www.icloud.com/keynote/0000GgDD1oe2TvwXEORDuP1Zw#밥플래닛
https://www.icloud.com/keynote/0000GgDD1oe2TvwXEORDuP1Zw#%EB%B0%A5%ED%94%8C%EB%9E%98%EB%8B%9B

2015년 10월 20일 (화) 오후 1:41, Jin, Heonkyu notifications@github.com님이 작성:

**Comment by hkjinlee** [comment]
제가 생각하는 컬러링 컨셉은 대충 이래요:
http://www.shutterstock.com/pic-296573297/stock-vector-set-of-color-vector-icons-ice-cream-soybean-paste-soup-coffee-bread-birthday-cake-rice-milk.html?src=csl_recent_image-4

**Comment by hkjinlee** [comment]
https://github.com/bobplanet/Bobplanet/blob/master/app/src/main/res/values/colors.xml 를 참조하면 현재 앱에서 활용중인 color code 나옵니다. 식판 메타포를 살짝 채용하고 아침-점심-저녁 색상을 탭으로 바꿔본 이미지 첨부합니다.

![ic_launcher](https://cloud.githubusercontent.com/assets/7744953/10639317/7786319a-784a-11e5-9b2c-86c960dcdea0.png)

**Comment by hkjinlee** [comment]
한글보다는 영어가 좌우 align이 맞아서 더 나아 보이네요.

![ic_launcher](https://cloud.githubusercontent.com/assets/7744953/10639670/747d8ba4-784c-11e5-860b-de1f8d2d323f.png)

**Comment by hkjinlee** [comment]
앱 아이콘은 일단 이대로 클로징합니다. 페북이나 네이버 로그인쪽에도 아이콘 제출해야 해서, 이 이상 미루면 나중에 손볼 데가 많아짐.
